services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: demo-nextjs-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3001}:${APP_PORT:-3001}"
